export enum Action {
  categoryCreate = 'category.create',
  categoryRead = 'category.read',
  categoryUpdate = 'category.update',
  categoryDelete = 'category.delete',
  productCreate = 'product.create',
  productRead = 'product.read',
  productUpdate = 'product.update',
  productDelete = 'product.delete',
  usersRead = 'users.read',
  usersUpdate = 'users.update',
  usersDelete = 'users.delete',
  orderCreate = 'order.create',
  orderRead = 'order.read',
  orderUpdate = 'order.update',
  orderDelete = 'order.delete',
  roleCreate = 'role.create',
  roleRead = 'role.read',
  roleUpdate = 'role.update',
  roleDelete = 'role.delete',
  authCreate = 'auth.create',
  authRead = 'auth.read',
}
