name: pre-deploy.yml

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STAGE: "production"
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      - name: 'Node.js 20.x'
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Build code'
        run: npm run build && find dist/main.js
      - name: 'Test DB connection'
        run: npm run migration:show
      - name: 'Sync DB'
        run: npm run migration:sync
      - name: 'Run migrations'
        run: npm run migration:run